<<<<<<< HEAD
development:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_dev.sqlite

test:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_test.sqlite

production:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_live.sqlite
=======
development:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_dev.sqlite

test:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_test.sqlite

production:
  adapter: sqlite3
  encoding: utf8
  database: shortened_urls_live.sqlite
>>>>>>> ee1ade3789529e0f3f67a4582857a561826ed79e
